Add 1.0.1 and Question FAQ
UpsilonNumworks/Upsilon-website pull request #38
Opened 2022-10-28 08:01 UTC by Cyber-Thibaut

Added information about the 1.0.1 maj and added the question about the disappearance of the USB menu in the settings from the FAQ

2022-10-28 08:24 UTC, Yaya-Cout requested changes
Can you explain in which app are the changes ? It is not very clear.

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/en.json
> +        "XNT" : "XNT Cyclique (Plusieurs appuis sur XNT changent le caractère inséré entre X, N, T et θ)",
Can you translate it ?

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/en.json
> +        "AddFunctionLiseuse" : "Additional functions in TRU (sums, products, integrals and binomial coefficients)",
```suggestion
        "AddFunctionLiseuse" : "Additional functions in URT (sums, products, integrals and binomial coefficients)",
```

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/en.json
> +        "BlockHardware" : "Blocking of hardwares tests in exam mode",
Can you rename to `BlockHardwareTests` ?
```suggestion
        "BlockHardware" : "Blocking of hardwares tests in exam mode"
```

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/en.json
> +        "CorrErrorBack" : "Fix syntax error when reverting",
Can you explain that it's in the reader app ?

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/en.json
> +        "AddUlab" : "Added `ulab.utils`.",
```suggestion
        "AddUlab" : "Added `ulab.utils`",
```

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/en.json
> +        "answer": "The USB protection has been integrated into the bootloader and therefore no longer needs a menu.",
```suggestion
        "answer": "The USB protection has been integrated into the bootloader and therefore no longer needs a menu."
```

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/en.json
> +  }
Why did you remove the last bracket ?

2022-10-28 08:24 UTC, Yaya-Cout commented on src/locales/fr.json
> +                "BlockHardware" : "Blocage des hardwares tests en mode examen",
Can you rename it too ?
```suggestion
                "BlockHardware" : "Blocage des hardwares tests en mode examen"
```

2022-10-28 08:52 UTC, Yaya-Cout requested changes
Can you also apply changes to the French translation ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "TxtTool" : "Larger text in toolboxes with automatic scrolling when text is too long",
Can you rename it to `ToolboxFontSize` ?
```suggestion
        "TxtTool" : "Larger text in toolboxes with automatic lateral scrolling when text is too long",
```

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "CorrPix" : "Fixed pixel shift on some icons in some themes",
Can you rename it to `FixShiftedIcon` or something similar ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
>        }
```suggestion
      },
```

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "NewPol" : "Changed font",
Can you rename to `NewFont` and edit the text to `New font` (I prefer this form, but it's just me)
```suggestion
        "NewPol" : "New font",
```

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "PyMaJ" : "MicroPython update from 1.17 to 1.19.1",
Can you rename it to `MicroPythonUpgrade` ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "PyLightControl" : "Control of brightness via `set_brightness` and `get_brightness`.",
Can you rename it to `PythonBrightnessControl` ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "AddFunctionLiseuse" : "Additional functions in URT (sums, products, integrals and binomial coefficients)",
Can you rename it to `AddUrtFunctions` or something similar ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "AddCaracURT" : "In the reader application, add extra characters in the URT (``f` and ``i`)",
Can you rename it to `AddCharactersUrt`

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "CorrBrownColor" : "Brown color correction in URT for the reader application",
Can you rename it to `FixBrownColorUrt` ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "CorrErrorBack" : "Fixed a syntax error when reverting in the reader application",
Can you rename it to `FixReaderErrorBack` ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "BlockHardware" : "Blocking of hardwares tests in exam mode"
Can you rename it to `BlockHardwareTests` ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
>    }
Why did you remove the last bracket ?

2022-10-28 08:52 UTC, Yaya-Cout commented on src/locales/en.json
> +        "PyItal" : "Italicized text in strings",
Can you explain that it's in the Python editor ?

2022-10-28 08:54 UTC, Yaya-Cout commented on src/locales/fr.json
>              }
```suggestion
            },
```

2022-10-28 09:18 UTC, Cyber-Thibaut commented
changes applied in all affected files (en/fr and releases.vue)

2022-10-28 09:27 UTC, Yaya-Cout commented on src/locales/fr.json
> +                "answer": "La protection USB a été intégrée au bootloader et n'as donc plus besoin de menu.",
```suggestion
                "answer": "La protection USB a été intégrée au bootloader et n'a donc plus besoin de menu.",
```

2022-12-05 16:32 UTC, Yaya-Cout requested changes
Can you apply these changes and reflect the on others files ?

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "CorrPix" : "Fixed pixel shift on some icons in some themes",
Why did you mark it as resolved ?

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "XNT" : "XNT Cyclic (Multiple presses of XNT change the character inserted between X, N, T and θ)",
```suggestion
        "CyclicXNT" : "XNT Cyclic (Multiple presses of XNT change the character inserted between X, N, T and θ)",
```

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "TxtItal" : "Italicized text in some places such as function definitions in the functions application and texts and comments in the Python editor",
```suggestion
        "AddItalize" : "Italicized text in some places such as function definitions in the functions application and texts and comments in the Python editor",
```

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "FixShiftedIcon" : "Shortcut Shift + Ans to go to the last used application",
```suggestion
        "ShiftAns" : "Shortcut Shift + Ans to go to the last used application",
```

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "CorrPix" : "Fixed pixel shift on some icons in some themes",
```suggestion
        "FixShiftedIcon" : "Fixed pixel shift on some icons in some themes",
```

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "Dim" : "Dimension in additional results when a unit is used",
```suggestion
        "DimInAdditionalsResults" : "Dimension in additional results when a unit is used",
```

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "PyCrash" : "Fixed a crash when opening scripts in the Python editor",
```suggestion
        "PythonCrash" : "Fixed a crash when opening scripts in the Python editor",
```

2022-12-05 16:32 UTC, Yaya-Cout commented on src/locales/en.json
> +        "CorrErrorBack" : "Fixed a syntax error when reverting in the reader application",
```suggestion
        "FixReaderErrorBack" : "Fixed a syntax error when reverting in the reader application",
```

2022-12-06 17:03 UTC, merged